[2024-03-03T03:41:56.965+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_data_files.get_files_3 scheduled__2016-12-15T00:00:00+00:00 [queued]>
[2024-03-03T03:41:56.979+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_data_files.get_files_3 scheduled__2016-12-15T00:00:00+00:00 [queued]>
[2024-03-03T03:41:56.980+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-03T03:41:57.000+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_files_3> on 2016-12-15 00:00:00+00:00
[2024-03-03T03:41:57.010+0000] {standard_task_runner.py:60} INFO - Started process 4632 to run task
[2024-03-03T03:41:57.016+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_data_files', 'get_files_3', 'scheduled__2016-12-15T00:00:00+00:00', '--job-id', '2114', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmpuugf2tti']
[2024-03-03T03:41:57.020+0000] {standard_task_runner.py:88} INFO - Job 2114: Subtask get_files_3
[2024-03-03T03:41:57.043+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-03T03:41:57.103+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_data_files.get_files_3 scheduled__2016-12-15T00:00:00+00:00 [running]> on host 716a53fa82e1
[2024-03-03T03:41:57.227+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_data_files' AIRFLOW_CTX_TASK_ID='get_files_3' AIRFLOW_CTX_EXECUTION_DATE='2016-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2016-12-15T00:00:00+00:00'
[2024-03-03T03:41:59.884+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-03T03:41:59.897+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=fetch_data_files, task_id=get_files_3, execution_date=20161215T000000, start_date=20240303T034156, end_date=20240303T034159
[2024-03-03T03:42:00.286+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-03T03:42:00.330+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
